BASE_URL = "https://ems2.panasonic.com.tw/api"
APP_TOKEN = "D8CBFF4C-2824-4342-B22D-189166FEF503"
USER_AGENT = "Dalvik/2.1.0 (Linux; U; Android 7.1.2; SM-G930K Build/N2G48H)"

SECONDS_BETWEEN_REQUEST = 2
REQUEST_TIMEOUT = 20

HTTP_EXPECTATION_FAILED = 417
HTTP_TOO_MANY_REQUESTS = 429

EXCEPTION_COMMAND_NOT_FOUND = "無法透過CommandId取得Commmand"
EXCEPTION_TOKEN_EXPIRED = "無法依據您的CPToken,auth取得相關資料"
EXCEPTION_INVALID_REFRESH_TOKEN = "無效RefreshToken"
