BASE_URL = "https://ems2.panasonic.com.tw/api"
APP_TOKEN = "D8CBFF4C-2824-4342-B22D-189166FEF503"
USER_AGENT = "okhttp/4.9.1"

SECONDS_BETWEEN_REQUEST = 2
REQUEST_TIMEOUT = 20
COMMANDS_PER_REQUEST = 6

EXCEPTION_COMMAND_NOT_FOUND = "無法透過CommandId取得Commmand"
EXCEPTION_DEVICE_OFFLINE = "deviceOffline"
EXCEPTION_DEVICE_NOT_RESPONDING = "deviceNoResponse"
EXCEPTION_DEVICE_JP_INFO = "503:DeviceJPInfo:aStatusCode"
EXCEPTION_DEVICE_JP_FAILED = ":DeviceJPInfo:GetCommandTransResult failed"
EXCEPTION_TOKEN_EXPIRED = "無法依據您的CPToken,auth取得相關資料"
EXCEPTION_INVALID_REFRESH_TOKEN = "無效RefreshToken"
EXCEPTION_CPTOKEN_EXPIRED = "此CPToken已經逾時"
EXCEPTION_REACH_RATE_LIMIT = "系統檢測您當前超量使用"
